pscanrules: update minimum commonlib version
Require 1.13.0 as minimum, the `HeartBleedScanRule` scan rule requires
that version.

Noticed while working on zaproxy/zaproxy#7765.
It would lead to an exception when installing the add-on, e.g.:
```
ERROR AddOnLoaderUtils - Failed to initialise: HeartBleedScanRule
java.lang.NoSuchMethodError: 'void CommonAlertTag.putCve(Map, String)'
    at HeartBleedScanRule.<clinit>(HeartBleedScanRule.java:76) ~[?:?]
…
```

Signed-off-by: thc202 <thc202@gmail.com>