zest: fix UI threading issues
Change ZestResultsTableModel to add the Zest results and clear the model
in the EDT to prevent UI related threading issues. Otherwise it could
lead to exceptions like:
   java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
when the EDT attempts to obtain the results.

Bump version and update changes in ZapAddOn.xml file.