Bugfix for groovy.lang.MissingMethodException
* Bugfix for groovy.lang.MissingMethodException

```
ERROR org.zaproxy.zap.extension.scripts.OutputPanel  - groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
java.lang.RuntimeException: groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getRequiredParamsNames() is applicable for argument types: () values: []
```

* added comments from js template regarding required and optional parameters
* Update CHANGELOG.md
* applied suggested patch for underlying issue