zest: validate cookie name not empty
Change ZestCookieDialog to validate that the cookie name is not empty.
Zest library requires a non-empty name:
 IllegalArgumentException: Cookie name may not be blank

Update changes in ZapAddOn.xml file.