ascanrulesAlpha: correct empty path handling
Change SourceCodeDisclosureFileInclusion to skip the scan if there's no
path to work with, preventing exceptions when handling it:
 StringIndexOutOfBoundsException: String index out of range: -2

Change ProxyDisclosureScanner to properly build the URI when the path is
empty (i.e. add "/" instead of "null"), which would lead to wrong host
being requested, e.g. "example.comnullIAACS".

Bump version and update changes in ZapAddOn.xml file.